-- ============================================================
--  HỆ THỐNG QUẢN LÝ SÂN BÓNG - PTIT
--  File: database.sql
--  Mô tả: Tạo CSDL PostgreSQL, bảng và dữ liệu mẫu
-- ============================================================

-- Chạy bằng psql:
--   psql -U postgres -f database.sql

SELECT 'CREATE DATABASE quan_ly_san_bong ENCODING ''UTF8'''
WHERE NOT EXISTS (
    SELECT 1 FROM pg_database WHERE datname = 'quan_ly_san_bong'
)\gexec

\connect quan_ly_san_bong

SET client_encoding = 'UTF8';
SET standard_conforming_strings = ON;

ALTER DATABASE quan_ly_san_bong SET client_encoding TO 'UTF8';

-- PostgreSQL stores Vietnamese correctly with UTF-8. If the server was built
-- with ICU support, this collation can be used for Vietnamese-aware ORDER BY:
--   ORDER BY ho_ten COLLATE "vi_vn"
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM pg_collation
        WHERE collprovider = 'i'
        LIMIT 1
    ) AND NOT EXISTS (
        SELECT 1
        FROM pg_collation
        WHERE collname = 'vi_vn'
    ) THEN
        EXECUTE 'CREATE COLLATION vi_vn (provider = icu, locale = ''vi-VN'')';
    END IF;
END
$$;

-- ============================================================
-- KIỂU DỮ LIỆU ENUM
-- ============================================================
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_vai_tro') THEN
        CREATE TYPE user_vai_tro AS ENUM ('admin', 'khach_hang');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_trang_thai') THEN
        CREATE TYPE user_trang_thai AS ENUM ('hoat_dong', 'bi_khoa');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'loai_san_bong') THEN
        CREATE TYPE loai_san_bong AS ENUM ('5 nguoi', '7 nguoi', '11 nguoi');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'san_trang_thai') THEN
        CREATE TYPE san_trang_thai AS ENUM ('hoat_dong', 'bao_tri');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'dat_san_trang_thai') THEN
        CREATE TYPE dat_san_trang_thai AS ENUM ('cho_xac_nhan', 'da_xac_nhan', 'da_huy', 'hoan_thanh');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'phuong_thuc_thanh_toan') THEN
        CREATE TYPE phuong_thuc_thanh_toan AS ENUM ('tien_mat', 'chuyen_khoan', 'vi_dien_tu');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'thanh_toan_trang_thai') THEN
        CREATE TYPE thanh_toan_trang_thai AS ENUM ('cho_thanh_toan', 'da_thanh_toan', 'hoan_tien');
    END IF;
END
$$;

CREATE OR REPLACE FUNCTION set_ngay_cap_nhat()
RETURNS trigger AS $$
BEGIN
    NEW.ngay_cap_nhat = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ============================================================
-- 1. BẢNG USERS (người dùng)
-- ============================================================
CREATE TABLE IF NOT EXISTS users (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ho_ten        VARCHAR(100)  NOT NULL,
    email         VARCHAR(100)  NOT NULL UNIQUE,
    mat_khau      VARCHAR(255)  NOT NULL,
    so_dien_thoai VARCHAR(15),
    vai_tro       user_vai_tro DEFAULT 'khach_hang',
    trang_thai    user_trang_thai DEFAULT 'hoat_dong',
    ngay_tao      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ngay_cap_nhat TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TRIGGER IF EXISTS trg_users_set_ngay_cap_nhat ON users;
CREATE TRIGGER trg_users_set_ngay_cap_nhat
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION set_ngay_cap_nhat();

-- ============================================================
-- 2. BẢNG SAN_BONG (sân bóng)
-- ============================================================
CREATE TABLE IF NOT EXISTS san_bong (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ten_san       VARCHAR(100)  NOT NULL,
    loai_san      loai_san_bong NOT NULL,
    gia_thue      NUMERIC(10,2) NOT NULL,
    mo_ta         TEXT,
    hinh_anh      VARCHAR(255) DEFAULT 'default.jpg',
    trang_thai    san_trang_thai DEFAULT 'hoat_dong',
    ngay_tao      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ngay_cap_nhat TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TRIGGER IF EXISTS trg_san_bong_set_ngay_cap_nhat ON san_bong;
CREATE TRIGGER trg_san_bong_set_ngay_cap_nhat
BEFORE UPDATE ON san_bong
FOR EACH ROW
EXECUTE FUNCTION set_ngay_cap_nhat();

-- ============================================================
-- 3. BẢNG DAT_SAN (đơn đặt sân)
-- ============================================================
CREATE TABLE IF NOT EXISTS dat_san (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       INTEGER       NOT NULL,
    san_id        INTEGER       NOT NULL,
    ngay_dat      DATE          NOT NULL,
    gio_bat_dau   TIME          NOT NULL,
    gio_ket_thuc  TIME          NOT NULL,
    so_gio        NUMERIC(4,1)  NOT NULL,
    tong_tien     NUMERIC(12,2) NOT NULL,
    trang_thai    dat_san_trang_thai DEFAULT 'cho_xac_nhan',
    ghi_chu       TEXT,
    ngay_tao      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ngay_cap_nhat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_dat_san_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_dat_san_san
        FOREIGN KEY (san_id) REFERENCES san_bong(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_dat_san_san_ngay ON dat_san (san_id, ngay_dat);
CREATE INDEX IF NOT EXISTS idx_dat_san_user ON dat_san (user_id);

DROP TRIGGER IF EXISTS trg_dat_san_set_ngay_cap_nhat ON dat_san;
CREATE TRIGGER trg_dat_san_set_ngay_cap_nhat
BEFORE UPDATE ON dat_san
FOR EACH ROW
EXECUTE FUNCTION set_ngay_cap_nhat();

-- ============================================================
-- 4. BẢNG THANH_TOAN (thanh toán)
-- ============================================================
CREATE TABLE IF NOT EXISTS thanh_toan (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dat_san_id      INTEGER       NOT NULL,
    so_tien         NUMERIC(12,2) NOT NULL,
    phuong_thuc     phuong_thuc_thanh_toan NOT NULL,
    trang_thai      thanh_toan_trang_thai DEFAULT 'cho_thanh_toan',
    ma_giao_dich    VARCHAR(100),
    ngay_thanh_toan TIMESTAMP,
    ghi_chu         TEXT,
    ngay_tao        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_thanh_toan_dat_san
        FOREIGN KEY (dat_san_id) REFERENCES dat_san(id) ON DELETE CASCADE
);

-- Dùng collation tiếng Việt cho các cột hiển thị nếu PostgreSQL có ICU.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_collation WHERE collname = 'vi_vn') THEN
        EXECUTE 'ALTER TABLE users
            ALTER COLUMN ho_ten TYPE VARCHAR(100) COLLATE "vi_vn"';

        EXECUTE 'ALTER TABLE san_bong
            ALTER COLUMN ten_san TYPE VARCHAR(100) COLLATE "vi_vn",
            ALTER COLUMN mo_ta TYPE TEXT COLLATE "vi_vn"';

        EXECUTE 'ALTER TABLE dat_san
            ALTER COLUMN ghi_chu TYPE TEXT COLLATE "vi_vn"';

        EXECUTE 'ALTER TABLE thanh_toan
            ALTER COLUMN ghi_chu TYPE TEXT COLLATE "vi_vn"';
    END IF;
END
$$;

-- ============================================================
-- DỮ LIỆU MẪU
-- ============================================================

-- Mật khẩu: admin123 (đã hash bằng bcrypt rounds=10)
INSERT INTO users (id, ho_ten, email, mat_khau, so_dien_thoai, vai_tro) VALUES
(1, 'Quản Trị Viên', 'admin@sanbong.vn', '$2a$10$qcgWmz.RQBBvgjx56wHk..10IhIC3l524UnUL6p1MrCyNH386MHTu', '0901111111', 'admin')
ON CONFLICT (id) DO NOTHING;

-- Mật khẩu: 123456 (đã hash bằng bcrypt rounds=10)
INSERT INTO users (id, ho_ten, email, mat_khau, so_dien_thoai, vai_tro) VALUES
(2, 'Nguyễn Văn An',   'nguyenvanan@gmail.com',  '$2a$10$YvDK3c5i8vogJtjqDD3qp.aU/zWYo3bzG6Bee.UjMIxhc869/7fpS', '0912345678', 'khach_hang'),
(3, 'Trần Thị Bình',   'tranthibibinh@gmail.com', '$2a$10$YvDK3c5i8vogJtjqDD3qp.aU/zWYo3bzG6Bee.UjMIxhc869/7fpS', '0923456789', 'khach_hang'),
(4, 'Lê Văn Cường',    'levancuong@gmail.com',    '$2a$10$YvDK3c5i8vogJtjqDD3qp.aU/zWYo3bzG6Bee.UjMIxhc869/7fpS', '0934567890', 'khach_hang')
ON CONFLICT (id) DO NOTHING;

INSERT INTO san_bong (id, ten_san, loai_san, gia_thue, mo_ta, trang_thai) VALUES
(1, 'Sân A1 - Nhà Thi Đấu', '5 nguoi', 200000, 'Sân cỏ nhân tạo cao cấp thế hệ 3, có mái che, đèn chiếu sáng tiêu chuẩn. Phù hợp thi đấu 5 người.', 'hoat_dong'),
(2, 'Sân A2 - Nhà Thi Đấu', '5 nguoi', 180000, 'Sân cỏ nhân tạo, không mái che, phù hợp ban ngày. Giá ưu đãi.', 'hoat_dong'),
(3, 'Sân B1 - Khu Thể Thao', '7 nguoi', 350000, 'Sân 7 người tiêu chuẩn thi đấu, cỏ nhân tạo Châu Âu, có khán đài mini.', 'hoat_dong'),
(4, 'Sân B2 - Khu Thể Thao', '7 nguoi', 320000, 'Sân 7 người, cỏ nhân tạo mới lắp 2024, hệ thống tưới tự động.', 'hoat_dong'),
(5, 'Sân C1 - Sân Vận Động', '11 nguoi', 600000, 'Sân 11 người tiêu chuẩn FIFA, cỏ tự nhiên, có phòng thay đồ và bãi giữ xe.', 'hoat_dong'),
(6, 'Sân D1 - Bảo Trì',      '5 nguoi', 200000, 'Sân đang bảo trì, tạm ngưng hoạt động.', 'bao_tri')
ON CONFLICT (id) DO NOTHING;

-- Dữ liệu đặt sân mẫu (dùng cho báo cáo doanh thu)
INSERT INTO dat_san (id, user_id, san_id, ngay_dat, gio_bat_dau, gio_ket_thuc, so_gio, tong_tien, trang_thai) VALUES
(1, 2, 1, CURRENT_DATE - 5, '08:00', '10:00', 2.0, 400000, 'hoan_thanh'),
(2, 3, 3, CURRENT_DATE - 4, '14:00', '16:00', 2.0, 700000, 'hoan_thanh'),
(3, 4, 5, CURRENT_DATE - 3, '17:00', '19:00', 2.0, 1200000,'hoan_thanh'),
(4, 2, 2, CURRENT_DATE - 2, '06:00', '07:30', 1.5, 270000, 'da_xac_nhan'),
(5, 3, 1, CURRENT_DATE - 1, '19:00', '21:00', 2.0, 400000, 'da_xac_nhan'),
(6, 4, 3, CURRENT_DATE,     '08:00', '10:00', 2.0, 700000, 'cho_xac_nhan'),
(7, 2, 1, CURRENT_DATE + 1, '15:00', '17:00', 2.0, 400000, 'cho_xac_nhan')
ON CONFLICT (id) DO NOTHING;

INSERT INTO thanh_toan (id, dat_san_id, so_tien, phuong_thuc, trang_thai, ngay_thanh_toan) VALUES
(1, 1, 400000,  'tien_mat',     'da_thanh_toan', CURRENT_TIMESTAMP - INTERVAL '5 days'),
(2, 2, 700000,  'chuyen_khoan', 'da_thanh_toan', CURRENT_TIMESTAMP - INTERVAL '4 days'),
(3, 3, 1200000, 'vi_dien_tu',   'da_thanh_toan', CURRENT_TIMESTAMP - INTERVAL '3 days')
ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('users', 'id'), COALESCE((SELECT MAX(id) FROM users), 1));
SELECT setval(pg_get_serial_sequence('san_bong', 'id'), COALESCE((SELECT MAX(id) FROM san_bong), 1));
SELECT setval(pg_get_serial_sequence('dat_san', 'id'), COALESCE((SELECT MAX(id) FROM dat_san), 1));
SELECT setval(pg_get_serial_sequence('thanh_toan', 'id'), COALESCE((SELECT MAX(id) FROM thanh_toan), 1));
